/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class riscvstorage_Native */

#ifndef _Included_riscvstorage_Native
#define _Included_riscvstorage_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     riscvstorage_Native
 * Method:    riscv_create_reader
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_riscvstorage_Native_riscv_1create_1reader
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     riscvstorage_Native
 * Method:    riscv_next_batch
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_riscvstorage_Native_riscv_1next_1batch
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
